// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, user_id, list_id, name, completed, created_at, updated_at)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	$3,
	$4,
	NOW(),
	NOW()
)
RETURNING id, user_id, list_id, name, completed, created_at, updated_at
`

type CreateItemParams struct {
	UserID    uuid.UUID
	ListID    uuid.UUID
	Name      string
	Completed bool
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.UserID,
		arg.ListID,
		arg.Name,
		arg.Completed,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListID,
		&i.Name,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemByID = `-- name: DeleteItemByID :exec
DELETE FROM items
WHERE id = $1 AND user_id = $2 AND list_id = $3
`

type DeleteItemByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	ListID uuid.UUID
}

func (q *Queries) DeleteItemByID(ctx context.Context, arg DeleteItemByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemByID, arg.ID, arg.UserID, arg.ListID)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, list_id, name, completed, created_at, updated_at
FROM items
WHERE id = $1 AND user_id = $2
`

type GetItemByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetItemByIDRow struct {
	ID        uuid.UUID
	ListID    uuid.UUID
	Name      string
	Completed bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetItemByID(ctx context.Context, arg GetItemByIDParams) (GetItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, arg.ID, arg.UserID)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Name,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsByUser = `-- name: ListItemsByUser :many
SELECT id, list_id, name, completed, created_at, updated_at
FROM items
WHERE user_id = $1
ORDER BY name ASC
`

type ListItemsByUserRow struct {
	ID        uuid.UUID
	ListID    uuid.UUID
	Name      string
	Completed bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListItemsByUser(ctx context.Context, userID uuid.UUID) ([]ListItemsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByUserRow
	for rows.Next() {
		var i ListItemsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Name,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemByID = `-- name: UpdateItemByID :one
UPDATE items
SET name = $4, completed = $5, updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND list_id = $3
RETURNING id, list_id, name, completed, created_at, updated_at
`

type UpdateItemByIDParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ListID    uuid.UUID
	Name      string
	Completed bool
}

type UpdateItemByIDRow struct {
	ID        uuid.UUID
	ListID    uuid.UUID
	Name      string
	Completed bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateItemByID(ctx context.Context, arg UpdateItemByIDParams) (UpdateItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, updateItemByID,
		arg.ID,
		arg.UserID,
		arg.ListID,
		arg.Name,
		arg.Completed,
	)
	var i UpdateItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Name,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
