// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, created_at, updated_at, hashed_password, email)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2
) 
RETURNING id, created_at, updated_at, email
`

type CreateUserParams struct {
	HashedPassword string
	Email          string
}

type CreateUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.HashedPassword, arg.Email)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, hashed_password, email FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.Email,
	)
	return i, err
}

const updatUser = `-- name: UpdatUser :one
UPDATE users
SET hashed_password = $2, email = $3, updated_at = NOW()
WHERE
	id = $1
RETURNING id, created_at, updated_at, email
`

type UpdatUserParams struct {
	ID             uuid.UUID
	HashedPassword string
	Email          string
}

type UpdatUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) UpdatUser(ctx context.Context, arg UpdatUserParams) (UpdatUserRow, error) {
	row := q.db.QueryRowContext(ctx, updatUser, arg.ID, arg.HashedPassword, arg.Email)
	var i UpdatUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
