// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lists.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (id, user_id, name, created_at, updated_at)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	NOW(),
	NOW()
)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateListParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRowContext(ctx, createList, arg.UserID, arg.Name)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteListByID = `-- name: DeleteListByID :exec
DELETE FROM lists
WHERE id = $1 and user_id = $2
`

type DeleteListByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteListByID(ctx context.Context, arg DeleteListByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteListByID, arg.ID, arg.UserID)
	return err
}

const getListByID = `-- name: GetListByID :one
SELECT id, name, created_at, updated_at
FROM lists
WHERE id = $1 AND user_id = $2
`

type GetListByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetListByIDRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetListByID(ctx context.Context, arg GetListByIDParams) (GetListByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getListByID, arg.ID, arg.UserID)
	var i GetListByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listsByUser = `-- name: ListsByUser :many
SELECT id, name, created_at, updated_at
FROM lists
WHERE user_id = $1
ORDER BY name ASC
`

type ListsByUserRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListsByUser(ctx context.Context, userID uuid.UUID) ([]ListsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListsByUserRow
	for rows.Next() {
		var i ListsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListByID = `-- name: UpdateListByID :one
UPDATE lists
SET name = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, name, created_at, updated_at
`

type UpdateListByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
}

type UpdateListByIDRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateListByID(ctx context.Context, arg UpdateListByIDParams) (UpdateListByIDRow, error) {
	row := q.db.QueryRowContext(ctx, updateListByID, arg.ID, arg.UserID, arg.Name)
	var i UpdateListByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
